device_sim:
  dome_radius: 0.0765
  dome_mass: 0.4
  dome_transparency: 0.4

  camera_xyz: "0.01 0 -0.005"
  camera_rpy: "0 -1.5707963 0"
  camera_hfov_deg: 80.0
  camera_width: 484
  camera_height: 366
  camera_update_rate: 30.0
  camera_image_topic: "/camera/image_raw"
  camera_info_topic: "/camera/camera_info"

  lidar_xyz: "-0.02 0 0.04445"
  lidar_rpy: "0 -1.5707963 0"
  lidar_topic: "/livox/lidar_raw"
  lidar_visualize: "true"
  lidar_update_rate: 10.0
  lidar_min_range: 0.1
  lidar_max_range: 200.0
  lidar_horizontal_fov_deg: 70.4
  lidar_vertical_fov_deg: 77.2
  lidar_samples: 24000
  lidar_downsample: 1
  lidar_csv: "package://livox_laser_simulation/scan_mode/avia.csv"
