FROM ros:noetic-ros-base

SHELL ["/bin/bash", "-c"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      iproute2 \
      procps \
      python3-rospy \
      ros-noetic-rosbridge-server \
      ros-noetic-tf2-web-republisher \
      ufw \
    && rm -rf /var/lib/apt/lists/*

ENV ROS_PACKAGE_PATH=/opt/ros/noetic/share:/catkin_ws/src
WORKDIR /catkin_ws

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/catkin_ws/docker/run_device.sh"]
